apiVersion: v1
kind: Service
metadata:
  name: tg-svc
  namespace: tigergraph
spec:
  ports:
  - port: 9090
    name: rest
  - port: 14240
    name: gui
  selector:
    app: tigergraph
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tg
  namespace: tigergraph
spec:
  serviceName: tg-svc
  replicas: 3
  selector:
    matchLabels:
      app: tigergraph
  template:
    metadata:
      labels:
        app: tigergraph
    spec:
      containers:
      - name: tigergraph
        image: tigergraph/tigergraph:4.2.2
        ports:
        - containerPort: 9090
        - containerPort: 14240
        env:
        - name: "SSH_PASSWORD"
          value: tigergraph
  volumeClaimTemplates:
  - metadata:
      name: tigergraph-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
